### PR TITLE
fix return documentation for check_sys_mapshaper

### PR DESCRIPTION
**Pull request by dblodgett-usgs**

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
Just noticed this in passing -- figured I'd throw in a quick fix.

**Comment by ateucher** [comment]
Thanks! Just one little typo ("mapjaper") and I'll be happy to merge

**Comment by dblodgett-usgs** [comment]
derp - apologies.

**Comment by ateucher** [comment]
Thanks!!

**Pull request merged**
